### ISSUE TITLE
Problem running MazeAntEnv

### ISSUE THREAD

**Issue by ahq1993** [florensacc/rllab-curriculum#4]
I am trying to run your algorithm on ant-maze. However, GaussianMLPPolicy gives the following assertion error.

assert isinstance(env_spec.action_space, Box)
AssertionError

Any idea, why is that a problem?

**Comment by florensacc** [comment]
I just ran the command
`python curriculum/experiments/goals/maze_ant/maze_ant_gan.py`
and got no error. Could you specify more what you are executing and whether you have done any modifications of the code?
Best,
CF

**Comment by ahq1993** [comment]
Thank you very much for your prompt response. I am trying to run a piece of it as follow: 

![image](https://user-images.githubusercontent.com/16362661/42476977-7d54e0ec-8384-11e8-80dd-c6f46dfb1b53.png)

**Comment by florensacc** [comment]
you are using the tensorflow policy in `sandbox.rocky.tf.policies` instead of the one in `rllab.policies` (which is in Theano). Our repository does not even have that sandbox directory, and we do not support the use of it with our experiments. If you still want to use tensorflow you need to update the code to use everything from `sandbox.rocky.tf`.
